// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WaterTankTool_WFA.Migrations
{
    [DbContext(typeof(WaterTankDbContext))]
    [Migration("20260609134528_MultiColumnAnchorBolt")]
    partial class MultiColumnAnchorBolt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WaterTankTool_WFA.Entity.AnchorBoltEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ab")
                        .HasColumnType("REAL");

                    b.Property<double?>("BoltSpacing")
                        .HasColumnType("REAL");

                    b.Property<double>("Db")
                        .HasColumnType("REAL");

                    b.Property<double?>("Dcone")
                        .HasColumnType("REAL");

                    b.Property<double>("Dh")
                        .HasColumnType("REAL");

                    b.Property<string>("DistributionMethod")
                        .HasColumnType("TEXT");

                    b.Property<double?>("E")
                        .HasColumnType("REAL");

                    b.Property<double?>("FcPrime")
                        .HasColumnType("REAL");

                    b.Property<double?>("Fu")
                        .HasColumnType("REAL");

                    b.Property<double?>("Fy")
                        .HasColumnType("REAL");

                    b.Property<double?>("Hef")
                        .HasColumnType("REAL");

                    b.Property<double?>("Mu")
                        .HasColumnType("REAL");

                    b.Property<int>("Nb")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Nbs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ns")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PedestalSize")
                        .HasColumnType("REAL");

                    b.Property<double?>("Phi")
                        .HasColumnType("REAL");

                    b.Property<double?>("Pu")
                        .HasColumnType("REAL");

                    b.Property<double>("Rb")
                        .HasColumnType("REAL");

                    b.Property<double?>("S")
                        .HasColumnType("REAL");

                    b.Property<double>("Tbp")
                        .HasColumnType("REAL");

                    b.Property<double?>("ThetaSeg")
                        .HasColumnType("REAL");

                    b.Property<double>("Tu")
                        .HasColumnType("REAL");

                    b.Property<double>("Vu")
                        .HasColumnType("REAL");

                    b.Property<double?>("WasherSize")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AnchorBoltEntity");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.BasePlateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("A")
                        .HasColumnType("REAL");

                    b.Property<double?>("A2")
                        .HasColumnType("REAL");

                    b.Property<double?>("BearingUtilization")
                        .HasColumnType("REAL");

                    b.Property<double>("Dbp")
                        .HasColumnType("REAL");

                    b.Property<double>("Dh")
                        .HasColumnType("REAL");

                    b.Property<double>("Fc_prime")
                        .HasColumnType("REAL");

                    b.Property<double?>("Fp")
                        .HasColumnType("REAL");

                    b.Property<double>("Fy")
                        .HasColumnType("REAL");

                    b.Property<double?>("L")
                        .HasColumnType("REAL");

                    b.Property<double?>("Mu")
                        .HasColumnType("REAL");

                    b.Property<int>("N")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nh")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OverturningMoment")
                        .HasColumnType("REAL");

                    b.Property<double?>("Phi_Pp")
                        .HasColumnType("REAL");

                    b.Property<double?>("Pu")
                        .HasColumnType("REAL");

                    b.Property<double?>("Rb")
                        .HasColumnType("REAL");

                    b.Property<double>("Ri")
                        .HasColumnType("REAL");

                    b.Property<double>("Ro")
                        .HasColumnType("REAL");

                    b.Property<double>("Rs")
                        .HasColumnType("REAL");

                    b.Property<double?>("ShellRadius")
                        .HasColumnType("REAL");

                    b.Property<double>("T")
                        .HasColumnType("REAL");

                    b.Property<double?>("T_req")
                        .HasColumnType("REAL");

                    b.Property<double>("Theta")
                        .HasColumnType("REAL");

                    b.Property<double?>("ThicknessUtilization")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BasePlateEntity");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.DeadLoadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Miscellaneous_Load")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DeadLoadEntity");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.LiveLoadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Design_Roof_Live_Load")
                        .HasColumnType("REAL");

                    b.Property<double>("Live_Load")
                        .HasColumnType("REAL");

                    b.Property<double>("Roof_Live_Load")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LiveLoadEntity");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.MaterialProperties", b =>
                {
                    b.Property<int>("MaterialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Density")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModulusOfElasticity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TensileUltimateStress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TensileYieldStress")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaterialNumber");

                    b.ToTable("MaterialProperties");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.SegmentProperties", b =>
                {
                    b.Property<int>("SegmentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Diameter")
                        .HasColumnType("REAL");

                    b.Property<double?>("DiameterFinal")
                        .HasColumnType("REAL");

                    b.Property<double?>("DiameterInitial")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightFinal")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightInitial")
                        .HasColumnType("REAL");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Thickness")
                        .HasColumnType("REAL");

                    b.HasKey("SegmentNumber");

                    b.ToTable("SegmentProperties");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.SeismicLoadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ai")
                        .HasColumnType("REAL");

                    b.Property<double>("Fa")
                        .HasColumnType("REAL");

                    b.Property<double>("Fv")
                        .HasColumnType("REAL");

                    b.Property<double>("Ie")
                        .HasColumnType("REAL");

                    b.Property<double>("Lambda")
                        .HasColumnType("REAL");

                    b.Property<double>("Ri")
                        .HasColumnType("REAL");

                    b.Property<double>("S1")
                        .HasColumnType("REAL");

                    b.Property<double>("Sa")
                        .HasColumnType("REAL");

                    b.Property<double>("Sd1")
                        .HasColumnType("REAL");

                    b.Property<double>("Sds")
                        .HasColumnType("REAL");

                    b.Property<string>("SiteClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Ss")
                        .HasColumnType("REAL");

                    b.Property<double>("Ti")
                        .HasColumnType("REAL");

                    b.Property<double>("Tl")
                        .HasColumnType("REAL");

                    b.Property<double>("Ts")
                        .HasColumnType("REAL");

                    b.Property<double>("V")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SeismicLoadEntity");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.SnowLoadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AreaSubjectedToSnow")
                        .HasColumnType("REAL");

                    b.Property<string>("Exposure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ExposureFactor")
                        .HasColumnType("REAL");

                    b.Property<double>("GroundSnowLoad")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightToConsider")
                        .HasColumnType("REAL");

                    b.Property<double>("ImportanceFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("RiskCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalSnowLoad")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SnowLoadEntity");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.TankProperties", b =>
                {
                    b.Property<int>("TankNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Centroid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectedArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalWeight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightOfSteel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightOfWater")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TankNumber");

                    b.ToTable("TankProperties");
                });

            modelBuilder.Entity("WaterTankTool_WFA.Entity.WindLoadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cf")
                        .HasColumnType("REAL");

                    b.Property<string>("Exposure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("G")
                        .HasColumnType("REAL");

                    b.Property<double>("I")
                        .HasColumnType("REAL");

                    b.Property<double>("Kd")
                        .HasColumnType("REAL");

                    b.Property<double>("Ke")
                        .HasColumnType("REAL");

                    b.Property<double>("Kzt")
                        .HasColumnType("REAL");

                    b.Property<double>("Q")
                        .HasColumnType("REAL");

                    b.Property<double>("V")
                        .HasColumnType("REAL");

                    b.Property<double>("Zg")
                        .HasColumnType("REAL");

                    b.Property<double>("alpha")
                        .HasColumnType("REAL");

                    b.Property<double>("lambda")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WindLoadEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
